name: "Continuous Deployment to main"
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/cd.yml@main
    with:
      image-name: snippet-runner
      env-name: main
  deploy_to_vm:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/deploy-prod.yml@main
    needs: push_to_registry
    secrets: inherit
    with:
      container-name: api-runner